### ISSUE TITLE
fingerprint

### ISSUE THREAD

**Issue by djlaser** [rk779/device_leeco_s2#2]
https://github.com/rk779/device_leeco_s2/blob/a03cf915766686d82af21c02a2f571e50d5290ee/rootdir/init.qcom.rc#L826
+    
 +service fingerprintd /system/bin/fingerprintd
 +    class late_start
 +    socket fpce stream 0666 system system
 +    user system

**Comment by djlaser** [comment]
fingerprint test

**Comment by rk779** [comment]
Fingerprint is fixed now

**Comment by rk779** [comment]
And yea that was needed. Thanks for the heads-up.
